language: perl
perl:
- "5.16"
- "5.14"
- "5.12"
- "5.10"

before_install:
- git config --global user.name "TravisCI"

install:
- cpanm --quiet --notest --skip-satisfied Dist::Zilla
- dzil authordeps | grep -vP '[^\w:]' | cpanm --quiet --notest --skip-satisfied
- dzil listdeps | grep -vP '[^\w:]' | cpanm --verbose

script:
- dzil smoke --release --author
