sudo: false

language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

install:
  - dzil authordeps --missing | cpanm --notest --quiet
  - dzil listdeps --author --missing --cpanm-versions | xargs cpanm --quiet --notest
  - dzil build

script:
  - dzil smoke --release --author

cache:
  directories:
    - local
