sudo: false

language: perl
perl:
- "5.20"
- "5.18"
- "5.16"
- "5.14"
- "5.12"
- "5.10"

before_install:
- cpanm Carton

install:
- carton install
- carton exec dzil authordeps --missing | cpanm

script:
- carton exec dzil smoke --release --author
