language: perl
perl:
- "5.18"
- "5.16"
- "5.14"
- "5.12"
- "5.10"

before_install:
- git config --global user.name "TravisCI"

install:
- cpanm --quiet --notest --skip-satisfied Carton
- carton install

script:
- carton exec dzil smoke --release --author
