=head1 NAME

App::Embra - build a site from parts

See how the development is progressing at L<the Trello board|https://trello.com/b/uGOfg0Zj>

=begin html

<p>
  <a href="https://travis-ci.org/dgholz/App-Embra">
    <img src="https://travis-ci.org/dgholz/App-Embra.png?branch=master" alt="Travis CI build status">
  </a>
</p>

=end html

=head1 HOW TO USE

=over

=item 1.

L</Set up your Perl environment>

=item 2.

L</Install App::Embra>

=item 3.

L<Configure your site>

=item 4.

L<Write content & build your site>

=back

=head2 Set up your Perl environment

You must use version 5.10 (or higher) of Perl, and have C<Carton> installed.

If you are using Windows, I recommend using  L<Strawberry Perl|http://strawberryperl.com/> (version 5.10 or higher). Install Carton with C<cpan install Carton>

For Mac & Linux, you probably have Perl 5.10 or higher already installed. If not, use L<plenv|http://plenv> to install a specific version. Install Carton with C<curl http://cpanmin.us/instal | perl - -- cpanm -l ~/perl5 Carton>.

=head2 Install App::Embra

Make a directory for your site, and create a file F<cpanfile> in that directory with this content:

    requires 'App::Embra'

Then open a terminal, change to your site's directory, and run C<carton> to install App::Embra & its dependencies.

=head2 Configure your site

Run C<carton exec embra init>; it will create a skeleton config in F<embra.ini>. Edit it to check that it guessed the right values (you probably want to change C<name> at least).

=head2 Write content & build your site

In your site's directory, create F<hello.md> with this content:

    ---
    title: greetings
    ----
    *HI THERE*

Then, from the same terminal, run C<carton exec embra collate>. Your site's files will appear in F<site/>; open C<file:///path/to/your/sites/directory/site/hello.html> to view the build site.
